theme: jekyll-theme-cayman

# Podcast Feed Settings
title:          Diacast
email:          hello@diacast.xyz
subtitle:       "A podcast about diabetes"
description:    "Diacast is a podcast about diabetes, in the widest sense of the word. We talk about technology, recipes, daily life, success stories, and a whole lot more. Sometimes we wander off to subjects that are unrelated to diabetes, because that's how conversations work."
subtitle:       "A podcast about diabetes"
url:            "https://diacast.xyz"
lang:           en_US
author:         "Cas Eli&euml;ns"
copyright:      "&#x2117; &amp; &#xA9; 2020"
