theme: jekyll-theme-cayman

# Podcast Feed Settings
title:          Diacast
email:          diacast@cascer1.space
subtitle:       "A podcast about diabetes"
description:    "Diacast is a podcast about diabetes, in the widest sense of the word. We talk about technology, recipes, daily life, success stories, and a whole lot more. Sometimes we wander off to subjects that are unrelated to diabetes, too."
subtitle:       "A podcast about diabetes"
url:            "https://cas.eliens.co/diacast"
lang:           en-US
author:         "Cas Eliëns"
copyright:      "&#x2117; &amp; &#xA9; 2020"
keywords:       "diabetes,diacast,insulin,kaleido,medtronic,omnipod,dexcom,openaps,androidaps,xdrip,nightscout"

collections:
  - people
  - platforms

defaults:
  -
    scope:
      path: "_posts/episodes"
      type: "posts"
    values:
      layout: "episode"
      hosts: "Adi, Brent, and Cas"
      author: "Cas Eliëns"
      excerpt_separator: <!--more-->
      explicit: "no"
      block: "no"
      type: "full"
      category: "episodes"
