theme: jekyll-theme-cayman

# Podcast Feed Settings
title:          Diacast
email:          hello@diacast.xyz
subtitle:       "A podcast about diabetes"
description:    "Diacast is a podcast about diabetes, in the widest sense of the word. We talk about technology, recipes, daily life, success stories, and a whole lot more. Sometimes we wander off to subjects that are unrelated to diabetes, too."
subtitle:       "A podcast about diabetes"
url:            "https://www.diacast.xyz"
lang:           en-US
author:         "Cas Eliëns"
copyright:      "&#x2117; &amp; &#xA9; 2020"


defaults:
  -
    scope:
      path: "episodes"
      type: "posts"
    values:
      layout: "post"
      author: "Cas Eliëns"
      excerpt_separator: <!--more-->
      explicit: "no"
      block: "no"
      type: "full"
